Repository openshift/must-gather-clean, pull requests merged in 2021-09, with the labels that each got.

#42 Scripts to generate RPMs for must-gather-clean
  .gitignore
  Makefile
  cmd/must-gather-clean/version.go
  hack/bump-version.sh
  hack/compile.sh
  hack/prepare-release.sh
  hack/rpm-local-build.sh
  hack/rpm-prepare.sh
  rpms/must-gather-clean.spec
Labels: lgtm, approved

#44 consistent MAC address obfuscation
  pkg/cli/cli.go
  pkg/obfuscator/generator.go
  pkg/obfuscator/ip.go
  pkg/obfuscator/ip_test.go
  pkg/obfuscator/mac_address.go
  pkg/obfuscator/mac_address_test.go
  pkg/obfuscator/tracker.go
  pkg/obfuscator/tracker_test.go
Labels: ok-to-test, lgtm, tide/merge-method-squash, approved

#45 Update OWNERS
  OWNERS
Labels: approved

#47 documenting schema obfuscators
  README.md
Labels: lgtm, tide/merge-method-squash, approved

#49 omission documentation
  README.md
Labels: lgtm, tide/merge-method-squash, approved

#50 increase ip formatting limits
  pkg/obfuscator/generator.go
  pkg/obfuscator/generator_test.go
  pkg/obfuscator/ip.go
  pkg/obfuscator/ip_test.go
  pkg/obfuscator/mac_address.go
  pkg/obfuscator/mac_address_test.go
Labels: lgtm, tide/merge-method-squash, approved

#46 Source git version from build-machinery-go Makefile
  cmd/must-gather-clean/version.go
  hack/bump-version.sh
  pkg/version/version.go
Labels: lgtm, approved

#52 contribution guidelines
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/stale.yml
  CONTRIB.md
  DEV.md
  README.md
Labels: lgtm, do-not-merge/hold, approved

#43 refactor io system and reporting
  .gitignore
  examples/basic.yaml
  examples/openshift_default.yaml
  go.mod
  pkg/cleaner/cleaning.go
  pkg/cleaner/cleaning_test.go
  pkg/cli/cli.go
  pkg/cli/cli_test.go
  pkg/input/filesystem.go
  pkg/input/filesystem_test.go
  pkg/input/input.go
  pkg/input/testfiles/test1/test1.yaml
  pkg/input/testfiles/test1/test2.yaml
  pkg/input/testfiles/test1/testdir/test3.yaml
  pkg/kube/kube_schema.go
  pkg/kube/kube_schema_reader.go
  pkg/kube/kube_schema_test.go
  pkg/obfuscator/domain.go
  pkg/obfuscator/ip.go
  pkg/obfuscator/keywords.go
  pkg/obfuscator/mac_address.go
  pkg/obfuscator/multi_obfuscator.go
  pkg/obfuscator/multi_obfuscator_test.go
  pkg/obfuscator/noop_obfuscator.go
  pkg/obfuscator/obfuscator.go
  pkg/obfuscator/regex.go
  pkg/obfuscator/target_obfuscator.go
  pkg/omitter/fileomitter.go
  pkg/omitter/fileomitter_test.go
  pkg/omitter/kubernetesresource.go
  pkg/omitter/kubernetesresource_test.go
  pkg/omitter/noop_omitter.go
  pkg/omitter/omitter.go
  pkg/omitter/reporting_omitter.go
  pkg/omitter/reporting_omitter_test.go
  pkg/output/output.go
  pkg/output/output_test.go
  pkg/reporting/reporter.go
  pkg/reporting/reporter_test.go
  pkg/schema/schema_reader.go
  pkg/traversal/report.go
  pkg/traversal/testfiles/test1/report.yaml
  pkg/traversal/traversal.go
  pkg/traversal/traversal_test.go
  pkg/traversal/worker.go
  pkg/traversal/worker_test.go
  vendor/modules.txt
Labels: lgtm, tide/merge-method-squash, approved

#54 contrib updates from code review
  .github/ISSUE_TEMPLATE/bug-report.md
  CONTRIB.md
  DEV.md
  README.md
Labels: lgtm, approved

#58 ip regex range limit
  pkg/obfuscator/ip.go
  pkg/obfuscator/ip_test.go
Labels: lgtm, approved

#55 add support for bash pipes
  README.md
  cmd/must-gather-clean/root.go
  pkg/cli/cli.go
  pkg/cli/cli_test.go
Labels: lgtm, approved

#59 installation docs + release prep
  DEV.md
  Makefile
  README.md
  hack/compile.sh
Labels: lgtm, tide/merge-method-squash, approved

#61 fix bug in reading json and line reader
  pkg/cleaner/cleaning.go
  pkg/cleaner/cleaning_test.go
  pkg/kube/kube_schema_reader.go
  pkg/kube/kube_schema_test.go
Labels: lgtm, approved

#62 domain schema mismatch
  pkg/cli/cli.go
  pkg/cli/cli_test.go
  pkg/obfuscator/domain.go
  pkg/obfuscator/domain_test.go
  pkg/schema/schema.go
  pkg/schema/schema.json
Labels: lgtm, approved

#60 Fix for a creation of new file incase of a static obfuscation scenarios
  pkg/cleaner/cleaning.go
  pkg/cleaner/cleaning_test.go
Labels: lgtm, tide/merge-method-squash, approved

#64 fix for domain name specificity
  README.md
  pkg/obfuscator/domain.go
  pkg/obfuscator/domain_test.go
Labels: lgtm, tide/merge-method-squash, approved

#66 Add a watermark when done
  pkg/cli/cli.go
  pkg/cli/cli_test.go
  pkg/watermarker/watermarker.go
  pkg/watermarker/watermarker_test.go
Labels: lgtm, tide/merge-method-squash, approved

#63 fixing typos and language in README
  README.md
Labels: lgtm, approved

#65 Track how many times patterns are obfuscated
  pkg/obfuscator/domain.go
  pkg/obfuscator/domain_test.go
  pkg/obfuscator/generator.go
  pkg/obfuscator/ip.go
  pkg/obfuscator/ip_test.go
  pkg/obfuscator/keywords.go
  pkg/obfuscator/keywords_test.go
  pkg/obfuscator/mac_address.go
  pkg/obfuscator/mac_address_test.go
  pkg/obfuscator/multi_obfuscator.go
  pkg/obfuscator/multi_obfuscator_test.go
  pkg/obfuscator/noop_obfuscator.go
  pkg/obfuscator/obfuscator.go
  pkg/obfuscator/regex.go
  pkg/obfuscator/regex_test.go
  pkg/obfuscator/target_obfuscator.go
  pkg/obfuscator/tracker.go
  pkg/obfuscator/tracker_test.go
  pkg/reporting/reporter.go
  pkg/reporting/reporter_test.go
Labels: lgtm, tide/merge-method-squash, approved

#70 Fix ambiguous IP obfuscator config
  pkg/obfuscator/ip.go
  pkg/obfuscator/ip_test.go
Labels: lgtm, approved

#68 support for re-use of the obfuscated reports
  pkg/cleaner/cleaning_test.go
  pkg/cli/cli.go
  pkg/obfuscator/domain.go
  pkg/obfuscator/domain_test.go
  pkg/obfuscator/ip.go
  pkg/obfuscator/ip_test.go
  pkg/obfuscator/keywords.go
  pkg/obfuscator/keywords_test.go
  pkg/obfuscator/mac_address.go
  pkg/obfuscator/mac_address_test.go
  pkg/obfuscator/regex.go
  pkg/obfuscator/regex_test.go
  pkg/obfuscator/target_obfuscator_test.go
  pkg/obfuscator/tracker.go
  pkg/reporting/reporter.go
  pkg/reporting/reporter_test.go
Labels: lgtm, approved

#71 add documentation for reports
  README.md
  examples/basic.yaml
  examples/openshift_default.yaml
  examples/openshift_omit_network.yaml
Labels: lgtm, approved

#73 fix underscore IP bug
  examples/openshift_default.yaml
  pkg/obfuscator/ip.go
  pkg/obfuscator/ip_test.go
Labels: lgtm, approved

#72 e2e test suite
  .gitignore
  Makefile
  pkg/cli/cli_e2e_test.go
  test/e2e.sh
  test/files/README.md
  test/files/must-gather-aws-report.yaml
  test/files/must-gather-azure-report.yaml
  test/files/must-gather-gcp-report.yaml
  test/files/must-gather-metal-report.yaml
  test/files/must-gather-vsphere-report.yaml
  test/files/report-generator.sh
Labels: lgtm, tide/merge-method-squash, approved

#75 ignore mco due to cert leaking
  Makefile
  examples/openshift_default.yaml
  examples/openshift_omit_network.yaml
  test/files/README.md
  test/files/must-gather-aws-report.yaml
  test/files/must-gather-azure-report.yaml
  test/files/must-gather-gcp-report.yaml
  test/files/must-gather-metal-report.yaml
  test/files/must-gather-vsphere-report.yaml
Labels: lgtm, approved

#76 Updated README
  README.md
Labels: ok-to-test, lgtm, approved
