Repository openshift/must-gather-clean, pull requests merged in 2021-08, with the labels that each got.

#3 Remove maintainers field from OWNERS file
  OWNERS
Labels: lgtm

#7 Added arjunrn as approver
  OWNERS
Labels: approved, lgtm

#8 Added a linter target with golangci-lint
  .gitignore
  .golangci.yaml
  Makefile
  cmd/must-gather-clean/root.go
  hack/ensure-golangci-lint.sh
  pkg/schema/schema_reader.go
  pkg/schema/schema_test.go
Labels: lgtm, approved

#11 Running linter as part of verify target
  Makefile
Labels: lgtm, approved

#9 Implemented input directory traversal
  go.mod
  pkg/cli/cli.go
  pkg/obfuscator/keywords.go
  pkg/obfuscator/keywords_test.go
  pkg/obfuscator/obfuscator.go
  pkg/omitter/fileomitter.go
  pkg/omitter/fileomitter_test.go
  pkg/omitter/omitter.go
  pkg/output/output.go
  pkg/output/output_test.go
  pkg/schema/schema.go
  pkg/schema/schema.json
  pkg/traversal/testfiles/test1/contents.yaml
  pkg/traversal/testfiles/test1/mg/nodes/another.yaml
  pkg/traversal/testfiles/test1/mg/nodes/test.yaml
  pkg/traversal/testfiles/test1/mg/pods/application.log
  pkg/traversal/testfiles/test1/mg/pods/manifests.yaml
  pkg/traversal/traversal.go
  pkg/traversal/traversal_test.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/modules.txt
Labels: lgtm, approved

#12 add support to obfuscate mac addresses
  pkg/cli/cli.go
  pkg/obfuscator/keywords.go
  pkg/obfuscator/keywords_test.go
  pkg/obfuscator/mac_address.go
  pkg/obfuscator/mac_address_test.go
  pkg/obfuscator/obfuscator.go
  pkg/obfuscator/replacement_reporter.go
  pkg/obfuscator/replacement_reporter_test.go
  pkg/traversal/traversal_test.go
Labels: lgtm, tide/merge-method-squash, approved

#1 Added basic README
  README.md
Labels: lgtm, do-not-merge/hold, approved

#14 Added regex obfuscation
  pkg/cli/cli.go
  pkg/obfuscator/regex.go
  pkg/obfuscator/regex_test.go
Labels: lgtm, approved

#16 replace go-jsonschema with more recent patching
  go.mod
  go.sum
  pkg/cli/cli.go
  pkg/schema/schema.go
  vendor/github.com/atombender/go-jsonschema/pkg/codegen/emitter.go
  vendor/github.com/atombender/go-jsonschema/pkg/codegen/model.go
  vendor/github.com/atombender/go-jsonschema/pkg/generator/generate.go
  vendor/github.com/atombender/go-jsonschema/pkg/generator/validator.go
  vendor/modules.txt
Labels: tide/merge-method-squash, approved

#13 Added a domain obfuscator which replaces all occurences of FQDNs
  pkg/cli/cli.go
  pkg/obfuscator/domain.go
  pkg/obfuscator/domain_test.go
  pkg/schema/schema.go
  pkg/schema/schema.json
Labels: lgtm, approved

#15 Added obfuscator for IP Addresses
  pkg/cli/cli.go
  pkg/obfuscator/ip.go
  pkg/obfuscator/ip_test.go
Labels: lgtm, approved

#18 Consistent replacements for obfuscated IP addresses
  pkg/cli/cli.go
  pkg/obfuscator/ip.go
  pkg/obfuscator/ip_test.go
  pkg/obfuscator/replacement_reporter.go
  pkg/obfuscator/replacement_reporter_test.go
  pkg/traversal/traversal_test.go
Labels: lgtm, approved

#17 Refactored input logic for traversal.
  pkg/cli/cli.go
  pkg/input/filesystem.go
  pkg/input/filesystem_test.go
  pkg/input/input.go
  pkg/input/testfiles/test1/test1.yaml
  pkg/input/testfiles/test1/test2.yaml
  pkg/input/testfiles/test1/testdir/test3.yaml
  pkg/traversal/testfiles/test1/contents.yaml
  pkg/traversal/testfiles/test1/mg/pods/pod1/application.log
  pkg/traversal/testfiles/test1/mg/pods/pod1/manifests.yaml
  pkg/traversal/testfiles/test1/mg/pods/pod2/application.log
  pkg/traversal/testfiles/test1/mg/pods/pod2/manifests.yaml
  pkg/traversal/traversal.go
  pkg/traversal/traversal_test.go
Labels: lgtm, approved

#19 File omission based on file glob
  pkg/input/filesystem.go
  pkg/input/filesystem_test.go
  pkg/omitter/fileomitter.go
  pkg/omitter/fileomitter_test.go
Labels: lgtm, approved

#20 Refactored the omit configuration schema
  pkg/cli/cli.go
  pkg/schema/schema.go
  pkg/schema/schema.json
  pkg/schema/testfiles/valid/simple.json
  pkg/schema/testfiles/valid/simple.yaml
Labels: lgtm, approved

#21 Validate the input for file omitter in New function
  pkg/cli/cli.go
  pkg/omitter/fileomitter.go
  pkg/omitter/fileomitter_test.go
  pkg/traversal/traversal_test.go
Labels: lgtm, approved

#22 Added reporting of replacements and omissions
  pkg/cli/cli.go
  pkg/traversal/report.go
  pkg/traversal/testfiles/test1/report.yaml
  pkg/traversal/traversal.go
  pkg/traversal/traversal_test.go
Labels: lgtm, approved

#23 Fix IP obfuscation generator
  pkg/obfuscator/ip.go
  pkg/obfuscator/ip_test.go
Labels: lgtm, approved

#25 add some basic example and dev docs
  DEV.md
  README.md
  examples/basic.yaml
Labels: lgtm, tide/merge-method-squash, approved

#28 fix flake with report ordering
  pkg/traversal/traversal.go
Labels: lgtm, approved

#27 mac detector should not match UUIDs anymore
  pkg/obfuscator/mac_address.go
  pkg/obfuscator/mac_address_test.go
Labels: lgtm, tide/merge-method-squash, approved

#26 add overwrite flag for the output folder
  cmd/must-gather-clean/root.go
  pkg/cli/cli.go
  pkg/output/output.go
  pkg/output/output_test.go
Labels: lgtm, tide/merge-method-squash, approved

#29 Allow dashes in IPv4 address pattern
  pkg/obfuscator/ip.go
  pkg/obfuscator/ip_test.go
Labels: lgtm, approved

#24 Kubernetes Resource omitter
  pkg/cli/cli.go
  pkg/input/filesystem.go
  pkg/input/input.go
  pkg/omitter/kubernetesresource.go
  pkg/omitter/kubernetesresource_test.go
  pkg/omitter/omitter.go
  pkg/traversal/traversal.go
Labels: lgtm, approved

#31 fixing ip false positive with OCP nightly versions
  pkg/obfuscator/ip.go
  pkg/obfuscator/ip_test.go
Labels: lgtm, approved

#30 Only obfuscated user supplied domains
  pkg/cli/cli.go
  pkg/obfuscator/domain.go
  pkg/obfuscator/domain_test.go
  pkg/schema/schema.go
  pkg/schema/schema.json
Labels: lgtm, approved

#32 introduce proper logging framework, replace panics and printfs
  cmd/must-gather-clean/root.go
  go.mod
  go.sum
  pkg/obfuscator/ip.go
  pkg/obfuscator/ip_test.go
  pkg/obfuscator/replacement_reporter.go
  pkg/obfuscator/replacement_reporter_test.go
  pkg/traversal/traversal.go
  vendor/github.com/go-logr/logr/LICENSE
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/discard.go
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-logr/logr/logr.go
  vendor/k8s.io/klog/v2/.gitignore
  vendor/k8s.io/klog/v2/CONTRIBUTING.md
  vendor/k8s.io/klog/v2/LICENSE
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/RELEASE.md
  vendor/k8s.io/klog/v2/SECURITY.md
  vendor/k8s.io/klog/v2/SECURITY_CONTACTS
  vendor/k8s.io/klog/v2/code-of-conduct.md
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/modules.txt
Labels: lgtm, tide/merge-method-squash, approved

#33 fix in reporting, mkdirs, docs + example
  .gitignore
  README.md
  cmd/must-gather-clean/root.go
  examples/openshift_default.yaml
  pkg/cli/cli.go
  pkg/output/output.go
  pkg/output/output_test.go
Labels: lgtm, tide/merge-method-squash, approved

#35 Exclude common non-sensitive IPs from obfuscation
  pkg/obfuscator/ip.go
  pkg/obfuscator/ip_test.go
Labels: lgtm, approved

#36 update schema to reflect the implementation
  pkg/schema/schema.go
  pkg/schema/schema.json
Labels: lgtm, approved

#34 Concurrent processing of input directory
  cmd/must-gather-clean/root.go
  pkg/cli/cli.go
  pkg/obfuscator/ip.go
  pkg/obfuscator/keywords.go
  pkg/obfuscator/obfuscator.go
  pkg/obfuscator/replacement_reporter.go
  pkg/traversal/traversal.go
  pkg/traversal/traversal_test.go
  pkg/traversal/worker.go
  pkg/traversal/worker_test.go
Labels: lgtm, approved

#37 Refactor of replacment reporting
  pkg/obfuscator/domain.go
  pkg/obfuscator/domain_test.go
  pkg/obfuscator/ip.go
  pkg/obfuscator/ip_test.go
  pkg/obfuscator/keywords.go
  pkg/obfuscator/keywords_test.go
  pkg/obfuscator/mac_address.go
  pkg/obfuscator/mac_address_test.go
  pkg/obfuscator/obfuscator.go
  pkg/obfuscator/regex.go
  pkg/obfuscator/regex_test.go
  pkg/obfuscator/replacement_reporter.go
  pkg/obfuscator/replacement_reporter_test.go
  pkg/obfuscator/tracker.go
  pkg/obfuscator/tracker_test.go
  pkg/traversal/traversal.go
  pkg/traversal/traversal_test.go
Labels: lgtm, approved

#38 fixing: fatal error: concurrent map read and map write
  pkg/obfuscator/tracker.go
Labels: lgtm, approved

#40 Obfuscation on folder names
  pkg/cli/cli.go
  pkg/input/input.go
  pkg/obfuscator/domain.go
  pkg/obfuscator/domain_test.go
  pkg/obfuscator/ip.go
  pkg/obfuscator/ip_test.go
  pkg/obfuscator/keywords.go
  pkg/obfuscator/mac_address.go
  pkg/obfuscator/obfuscator.go
  pkg/obfuscator/regex.go
  pkg/obfuscator/regex_test.go
  pkg/obfuscator/target_obfuscator.go
  pkg/obfuscator/target_obfuscator_test.go
  pkg/output/output.go
  pkg/output/output_test.go
  pkg/schema/schema.go
  pkg/schema/schema.json
  pkg/traversal/traversal.go
  pkg/traversal/traversal_test.go
  pkg/traversal/worker.go
Labels: lgtm, tide/merge-method-squash, approved
